### ISSUE TITLE
Verifier.checkCharacterData -> Verifier.removeNonCharacterData method needed

### ISSUE THREAD

**Issue by jjYBdx4IL** [hunterhacker/jdom#141]
Applies also to other XML character groups/classes.

The required method should allow the user to handle content that cannot be guaranteed to be XML-compatible. It should allow the user to choose between just removing the invalid chars, or to replace them using non-XML-escape strategies like Java unicode escape (0x0000 -> \u0000) or simply replacing them by the <?> UTF character.

Maybe this mechanism should be exposed in two ways: one way would be through the suggest public methods that the user can use himself to avoid IllegalDataException. The other way would be as a generic strategy embedded maybe into the Format class (Format.enableFailSafeStrategy(...)).

**Comment by rolfl** [comment]
This issue raises a number of reliabilitty and compatibility concerns. Specifically:

1. How to report characters that are removed?
2. How to specify replacement strategies
3. How to ensure replacement strategies result in still-valid XML (in the encoding being used).

Additionally, the concept being considered would be relatively easy to implement outside of JDOM - calling JDOM methods with pre-parsed/replaced/sanitized content.

**Comment by jjYBdx4IL** [comment]
ofc it would be easy to implement. however, it would also be ugly to implement. Implementing a wrapper lib for just that?

**Comment by rolfl** [comment]
@jjYBdx4IL - you have to also realize that JDOM is downloaded more than 160,000 times a month (almost 2million a year). an API change like the one you suggest is not easy to do in a way that maintains the stability and reliability expected from JDOM. Further, it has been the philosophy of JDOM from the beginning to faithfully represent what the programmer asks, and to faithfully throw an exception when that is not possible. Softening that philosophy by changing things in the representation and not telling the user, is a problem because the users/programmers can no longer rely on JDOM's process.
