### ISSUE TITLE
SAXBuilder.build(Reader) does not return (endless loop?)

### ISSUE THREAD

**Issue by znerd** [hunterhacker/jdom#148]
This is an issue I encountered on JDOM 2.0.6.

Code to reproduce:

```java
String xmlString = "<!DOCTYPE html PUBLIC\n\"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><abcd/>";
SAXBuilder saxBuilder = new SAXBuilder();
StringReader stream = new StringReader(xmlString);
Document document = saxBuilder.build(stream);
```

The last statement never returns. Apparently something is looping internally.

**Comment by rolfl** [comment]
THere's not an internal loop.... in this case, because there is a DTD, the XML parser (xerces) is obliged to locate the DTD specification to ensure that any entities in the XML can be resolved, etc.

So, the xerces parser is trying to download: http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd 

Unfortunately, that page seems to be hanging right now. Click on the link above, and see.

Additionally, there was this issue before: http://www.w3.org/blog/systeam/2008/02/08/w3c_s_excessive_dtd_traffic/

and it seems to be the case now that they are throttling it for everything, not just Java, and others. Changing the user-agent for me made no difference though... actually, there's a 15 second delay if I set: `-Duser.agent="JDOM Initialization Strategy"`

Here's some test code:

```package net.tuis.jdomsupp;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;

import org.jdom2.JDOMException;

public class InfLoop {
    
    private static final long start = System.currentTimeMillis();
    
    private static final void log(String message) {
        long millis = System.currentTimeMillis() - start;
        System.out.printf("%8.3fs : %s\n", millis / 1000.0, message);
    }
    
    public static void main(String[] args) throws JDOMException, IOException, URISyntaxException {
        
        URL dtdu = new URI("http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd").toURL();
        log("Built URL: " + dtdu);
        HttpURLConnection dtdcon = (HttpURLConnection) dtdu.openConnection();
        log("Opened Connection to: " + dtdu);
        ByteArrayOutputStream dump = new ByteArrayOutputStream();
        String encoding = dtdcon.getContentEncoding();
        log("Got Encoding: " + encoding);
        try (InputStream dtdread = dtdcon.getInputStream()) {
            byte[] buffer = new byte[4096];
            int len = 0;
            while ((len = dtdread.read(buffer)) >= 0) {
                log("Read bytes: " + len);
                dump.write(buffer, 0, len);
            }
        }
        log("System downloaded: " + dump.size());
        String dtd = new String(dump.toByteArray(), encoding == null ? "UTF-8" : encoding);
        
        System.out.println(dtd);
        
    }

}
```

That code produces a 15 second delay for me with a custom user agent:

```   0.047s : Opened Connection to: http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd
  15.173s : Got Encoding: null
  15.173s : Read bytes: 24
```

In the past I wrote the "Resolver" project here, to deal with this problem in a specific way. The notes I put in the readme are worth reading regardless of whether you use the code: https://github.com/rolfl/Resolver

**Comment by znerd** [comment]
Ah, thanks for the quick and very useful response.

I fixed the issue by using a simple `NoOpEntityResolver`:

```java
public class NoOpEntityResolver implements EntityResolver {
    @Override
    public InputSource resolveEntity(String publicId, String systemId) {
        return new InputSource(new StringReader(""));
    }
}
```

For me, that's sufficient.
