### ISSUE TITLE
Native API crash is observed if xpath lookup is executed on the document with special unicode characters 

### ISSUE THREAD

**Issue by mykola-mokhnach** [hunterhacker/jdom#179]
```

F/art     (18983): art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: il
legal start byte 0xf0

```

The original issue is described in https://github.com/appium/appium/issues/13190

The crash itself: https://gist.github.com/Sitheek/02c69af331d6af550fab2df89400f45d#file-logcat-L2778

I do understand this is the problem of the Android system API itself, but it would be interesting to know if there's any good workaround we could apply in the client code to avoid this error and make xpath queries  with unicode chars working. Thanks

**Comment by rolfl** [comment]
Noted - not sure how to debug/reproduce. Also, from the stack it's clear that the issue is lower level than JDOM. JDOM is not in a position to pre-inspect content and change behaviour depending on the implementation of lower-level libraries.

Similar to this comment, it's a 3rd-party bug, and we're not in the business of trying to work around it.

Given the time elapsed, and the lack of updates both here and on https://github.com/appium/appium/issues/13190#issuecomment-529948723 - it appears that newer 3rd-party code probably has the issues  resolved.
