### ISSUE TITLE
Is there any way to keep attribute order?

### ISSUE THREAD

**Issue by helpermethod** [hunterhacker/jdom#182]
Hi,

I'm using JDOM to make some automated changes to an XML document. This works fine, JDOM keeps the comments and formatting intact, so that only the updated element is shown in the version control diff.

But there is still one minor problem: the root element has several attributes which get reordered, which lets the version control show unnecessary modifications.

Is there some way to keep the attribute order intact?

**Comment by hunterhacker** [comment]
I feel your pain.  Which is why JDOM actually keeps attribute order. 

But the standard XML parsers don't.  You're using SAXBuilder?  It's not reporting the original order to JDOM so that it can be preserved.  Maybe you can find an alternate parser and use a builder against it. Nothing says a SAX or DOM parser HAS to ignore attribute order, they just tend to.
