### ISSUE TITLE
When outputting XML is there some way to only keep the XML declaration if it already exists?

### ISSUE THREAD

**Issue by helpermethod** [hunterhacker/jdom#183]
Hi,

in order to keep the number of modifications on an XML document small, I would like to keep the 
XML declaration if it is present but *not* add it if it is missing.

Is seems `Format` will add *or* omit the declaration, right?

**Comment by hunterhacker** [comment]
JDOM does not get informed by the XML parsers if there was an XML declaration or not. So while the XMLOutputter lets you control if you want one in the output, there’s no way to make that decision based on the source document unless you peek yourself at the source document.  SAX and DOM by design don’t report on if the declaration is there or not, because it’s not semantically meaningful, so if you’re building using a SAX or DOM parser you won’t know if it was there or not.
