### ISSUE TITLE
no longer maintained

### ISSUE THREAD

**Issue by SingingBush** [hunterhacker/jdom#219]
there hasn't been any changes made or PR's reviewed/merged in a while. If this project is now defunct it's worth putting something to that effect in the readme and making the repo read-only. Perhaps worth looking out for another maintainer

**Comment by hunterhacker** [comment]
Am I still here? Yes.

Do I spend time on JDOM? Not really.

Why not? Well, it's been about 25 years since we started this. A guy's interests move on.

Is there a lot of work to be done? Not really. We shipped what we wanted to ship.

Should we find another maintainer? I'd be happy for someone else to step up and implement what they find important. I'd review everything and gate-keep the final step, out of security concerns.

Is that you? Lemme know.

**Comment by SingingBush** [comment]
I maintain a project on maven central that makes use of jdom so I'm happy to make further pull requests. #210 and #211 could be initial steps. I would like to have further 2.0.* releases with updated dependencies and no breaking API changes but am also interested in a new version (perhaps v3) that fully supports JPMS via a module-info.java and targets JDK 11+
